### ISSUE TITLE
Please Choose Android or iOS?

### ISSUE THREAD

**Issue by murffmade** [guidoPaglie/mobile-screen-resolutions#1]
When I open the window as instructed I am asked to "Please choose Android or iOS" but there is nowhere that I can find to make this choice. What am I doing wrong?

**Comment by guidoPaglie** [comment]
Hi! First, thank you by using the package, hope it helps! 
Where do you see  "Please choose Android or iOS" ? Maybe I forgot to update somewhere.
On the other hand, are you using the last version ? 

Anyway, it works in any platform you use, it doesn't matter if you are in Android or iOS. As you can see in the window, you can choose the resolution.

**Comment by murffmade** [comment]
You're welcome - thank you for working on it! It looks like it's going to be very helpful --- I have it installed - I click "Open Window" and I get the attached window with the Please choose Android or iOS messaging. 

![Untitled-1](https://user-images.githubusercontent.com/66485528/85794708-ab4a2b80-b6fc-11ea-94f5-f9586e6fba54.png)
![Untitled-2](https://user-images.githubusercontent.com/66485528/85794710-abe2c200-b6fc-11ea-8898-c67bf81f1d5a.png)

**Comment by guidoPaglie** [comment]
Oh yes I see! You have to choose as Platform Android or iOS. You are surely on Desktop
File -> Build Settings -> Andoird/iOS
